---
- name: inventory creation in memory
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    managed_hosts: "{{ managed_hosts_survey | split('\n') | map('trim') | difference(['']) }}"
  tasks:
    - ansible.builtin.debug:
        var: managed_hosts

    - name: Run validations on Survey data
      ansible.builtin.include_role:
        role: survey
      vars:
        hosts_provided: "{{ managed_hosts }}"

    - name: Load managed hosts group
      ansible.builtin.add_host:
        name: "{{ item }}"
        groups: mgmt_hosts
      loop: "{{ mgmt_hosts }}"

- name: Collecting facts
  hosts: all
  gather_facts: no
  tasks:
    - name: gather required facts
      ansible.builtin.setup:
      register: connection
      ignore_unreachable: true
      ignore_errors: true
    
    - block:
        - name: Register permissions denied hosts
          ansible.builtin.include_role:
            name: liverpool.automation.errors_report
          vars:
            error_message: "Error en autenticación ssh"
          when: '"Permission denied" in connection.msg'

        - name: Register timeout connection
          ansible.builtin.include_role:
            name: liverpool.automation.errors_report
          vars:
            error_message: "Conexión ssh con timeout"
          when: '"Connection timed out" in connection.msg'

        - name: Register possible python errors
          ansible.builtin.include_role:
            name: liverpool.automation.errors_report
          vars:
            error_message: "Error probablemente causado por python"
          when: 'connection.rc is defined'

        - name: Discard unreachable hosts
          ansible.builtin.fail:
            msg: "{{ connection.msg }}"
      when:
        connection.unreachable is defined or connection.rc is defined


- name: test errors report
  hosts: all
  tasks:
    - name: error tasks
      ansible.builtin.shell: |
        eco "Fail echo"
      register: error
      ignore_errors: true

    - block:
        - name: register error
          ansible.builtin.include_role:
            name: liverpool.automation.errors_report
          vars:
            error_message: esto es un error
      when: error.rc is defined
